spring:
   profiles:
     active: dev 
---
server:
  port: 8888
  

spring:
  profiles: dev
  application:
    name: Cloud-Consume #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

eureka:
  client:
    registerWithEureka: false # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔     
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka

---
server:
  port: 8888
  

spring:
  profiles: pvd
  application:
    name: Cloud-Consume #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
eureka:
  client:
    registerWithEureka: false # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔     
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka